version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: parserRoot123
      MYSQL_DATABASE: parser
      MYSQL_USER: parser-user
      MYSQL_PASSWORD: parser-user-passwd123
